### ISSUE TITLE
Running a hosted server?

### ISSUE THREAD

**Issue by anissen** [5Mixer/mphx#14]
This is not an issue directly related to this library but is definitely relevant.

Have you managed to set up a server somewhere and get clients connected to it (ie. not just running locally)?

---

_Rant about my attempt setting up a server on [heroku](https://heroku.com/):_

I've used the [haxe buildpack](https://github.com/keroxp/heroku-buildpack-haxe) and created a `build.hxml` in the root directory that automatically builds the server. That works great. Also, being able to deploy using simply `git push heroku my_branch:master` from the command line is awesome.

Actually running the server application was a bit of a problem. The server was not allowed to be run directly from the `build.hxml` as heroku would flag the deployment-process as having stalled and terminate the instance. Additionally, executing commands on the heroku instance spawns a _new_ instance that _doesn't_ have access to haxe, haxelib and neko. Also, trying to execute a C++ version of the server application fails with a socket library missing error.
A workaround for running the application from `build.hxml` was to create a bash script that executes the neko application _in the background_ and execute that script from `build.hxml`.

My server is running at anissen-tic-tac-toe-server.herokuapp.com:4325, however I haven't yet managed to connect to it (it _may_ very well be due to some missing heroku-specific configuration). I've tried connecting using both websockets and TCP but without any luck. The connection errors _may_ also be related to not being able to correctly look-up the IP address for the domain.

**Comment by 5Mixer** [comment]
First of all, thank you very much for being so eager to use and try the library!

I have not yet hosted it online, although tonight I will run one. I have some Digital Ocean (vps) credits, so I can run it on that.

I've never personally used heroko. With digital ocean it's just like having access to another computer, so I would just ssh in, install haxe, install the packages, clone the mphx project and run it. From what I gather, heroko does this but everything has to be installed, because a fresh install is provided each time. I'm not too sure about that, correct me if I am wrong.

I'll make a video of me trying to set it up with digital ocean tonight, and do some more research into making this work with heroko. Thanks for being the first to try this!

**Comment by 5Mixer** [comment]
I'm going to close this, because I can't really find what I can do with the library to help your situation with heroku - I can only say that mphx works on full vps's like Microsoft Azure and Digital Ocean. If anyone does happen to know a solution though, please do comment.
