### ISSUE TITLE
Callback on disconnection

### ISSUE THREAD

**Issue by jscott1989** [5Mixer/mphx#22]
Is it possible to get a callback when a connection is closed?

**Comment by yannsucc** [comment]
actually, you must "patch"  the loseConnection() function into mphx.tcp.Connection (by calling a callback or a signal here)

**Comment by 5Mixer** [comment]
Yep, this should be fairly easy. Disconnect handlers are kind of scattered through the code base, but I'll try to put an `onDisconnect` variable function in `IServer` and `IClient`, and call it from the different connections. Thanks for raising the issue.

**Comment by 5Mixer** [comment]
Last 2 commits should resolve this.

I don't even know if it compiles now, I'm really busy and this is the most I can do right now. I'll test soon.

**Comment by 5Mixer** [comment]
Should be resolved. Most classes now have a variable function called `onConnectionClose`. On the client it is of type `String->Void`. The string argument is the reason for the connection to close. It might not be too useful, but I think it is good to keep it there. On the server, the type is `IConnection->Void`. It doesn't include the reason for termination because it's unlikely this will contain anything useful. IConnection is of course just the connection that was closed.

I hope this resolves the issue, any feedback feel free to comment/raise another issue. Cheers!

**Comment by jscott1989** [comment]
Just tried this and it works perfectly. Thanks
