### ISSUE TITLE
Serverside loop?

### ISSUE THREAD

**Issue by ghost** [5Mixer/mphx#31]
Since server.start(); is the last function that has to be called, is there a way around this so that I can simutaniously run a server-side loop? 
Or is the idea of a event driven server to avoid this?  
example:
`while (true) {
    serverDate = Date.now().getTime();
    serverDateTwo = Date.now().getTime();
    time = Timer.stamp();
    localTime += serverDate / 1000;
    Sys.sleep(0.4);
}`

**Comment by ghost** [comment]
Closing this after I found this: https://github.com/5Mixer/mphx/blob/master/example/haxeflixel/pong/server/Main.hx

**Comment by 5Mixer** [comment]
Absolutely, this is something that is certainly encouraged if the loop needs to do more than just, well, run. Check out this example https://github.com/5Mixer/mphx/blob/master/example/haxeflixel/pong/server/Main.hx , it has a custom loop.

The idea behind making a custom loop is before the loop starts, you call the listen method, and somewhere in the loop, you call server.update(delta).

In the example, I call the update function, which in turn tells all game objects to obey physics, etc.

Hope this helped.



On 19 Jun 2016, at 9:36 am, Linus Jakobsson <notifications@github.com<mailto:notifications@github.com>> wrote:


Since server.start(); is the last function that has to be called, is there a way around this so that I can simutaniously run a server-side loop?
Or is the idea of a event driven server to avoid this?

example:
while (true) {
serverDate = Date.now().getTime();
serverDateTwo = Date.now().getTime();
time = Timer.stamp();
localTime += serverDate / 1000;
Sys.sleep(0.4);
}
