### ISSUE TITLE
Room, Room vairable, users etc.

### ISSUE THREAD

**Issue by flashultra** [5Mixer/mphx#4]
It will be good if server have room variables, users etc. As very good reference for the similar server  
  http://docs2x.smartfoxserver.com/
  http://docs2x.smartfoxserver.com/api-docs/asdoc/

**Comment by 5Mixer** [comment]
Thanks for raising the issue! It's something I do plan on working on. In reality, I think the issue comes down to storing unique data inside rooms and connections. At the moment, (in the examples I have written), this is done with a map that connects a room or a connection to game specific data, however I don't see this as a viable solution for bigger, more complex games. 

I may as well post my thoughts on resolving this here.

A room can either be a typed room, or a standard room. A standard room (ie - What is currently in the codebase) simply stores an array of 'Connections'. A typed room (eg new TypedRoom<UserType>) is one in which the class of the user is specified. In this way, the room will only expect rooms of a specific class.

Remember though, that rooms are just arrays of connections. Nothing more, really.

So that kind of deals with rooms. What about storing connection data, without using a map?

Well, technically, this is a little more complex, because there are loads of different protocols and different classes that deal with connections in different ways, though websockets, server/client, etc. The ideal way to deal with this is to have one public 'connection' class that is created by each individual class, (websocket, tcp server, etc). It's kind of already done, kind of not. Interfaces and things need to be made.

Don't know how much of this you understand or agree with, it's kind of notes for future things I need to do. Thanks for raising the issue! It's wip.

**Comment by anissen** [comment]
I'm not sure I really understand what @flashultra is asking for in the issue. However, I think it's important to keep rooms (and everything else) simple and not make assumptions about how the library is used.

That being said, the [Cloak](https://github.com/incompl/cloak/) library has [this definition of a room API](https://github.com/incompl/cloak/wiki/RoomAPI). But again, please refrain from making implementations that are too specific. If need be, they might be part of some other optional part of the library (e.g. under a different namespace or repository).

**Comment by 5Mixer** [comment]
Yes, rest assured that my aim is not for rooms and connections to contain lots of methods, my aim is only to make them entirely customisable for any specific game.

Tomorrow is obviously the weekend (huzzah) so I'll work it more then.

**Comment by flashultra** [comment]
For me , there should have two main classes - room and user . Room should accept user class ( join, leave, send message) , not connection class. Connection should be part of user class. Not sure what is benefit to have standard room only with connections. At least what is need for each user in the room is username and userid . Also for user class is good to have some kind of user variables ( if need to store some user info - rating, level ). Same for room - room should have - room name,room id,  max user allowed to join , .. and custom variables ( such as min rank for player to join in game, password for the room ( if room is protected) and so on)  
 The idea for one connection class sounds good. This connection class can be part of user class , if accept to have user as main class. 
 For what I saw this lobrary Cloak use same conception - Room and User classes and each room can accept user classes

**Comment by 5Mixer** [comment]
Alrighty, after all this, I've worked on an extremly quick (too quick?) way of doing things, that is not type safe (unless a cast is used). You can see it in commit cb4a43744a8db, there is just a dynamic data variable, where you can store user data, player position, etc. I thought a lot about different (much more complex) methods. You can see why I didn't choose them below.
-  Using Factories (Passing in a function that generates and returns a custom user class, that extends Connection) - Still not type safe, only advantage is it would mean being able to do `connection.score` rather than `connection.data.score`.
-  Passing in a class, so it is type safe - Means the server can only ever have one type of 'user'; too restrictive.

So yeah, the basic solution is to just have a dynamic data variable in users.

"But what about rooms?" Rooms are just fancy arrays of connection. You can just extend them yourself!

```
class fancyRoom extends mphx.server.Room {

    public var bullets = new Array<Bullet>();
    public var activePlayer:Connection;

    public function new (){

    }

    public function freezeEveryOne () {
        for (connection in connections){
            connection.data.isFrozen = true;
        }
    }
}
```

@flashultra, your suggestions are great! I don't want to put to many of those variables in the room/connection class (rating, passwords etc) because it's likely that people will make games or applications where those are not needed. The 'max users' is totally valid though, I'll include that soon.

**Comment by 5Mixer** [comment]
@flashultra The Max connections variable is now actually used. 105a4416f9bb1dc187cc8d4eb3c9086fc44cb81f

**Comment by 5Mixer** [comment]
Variables such as room name can really easily be made by extending room, (shown in my comment two up). 

I think this addresses most things. Sorry about this being such a long conversation for such little changes. Please feel free to comment/raise another issue if something still feels incomplete or lacking in this regard, I know the solution of using a dynamic variable isn't a perfect one.
