### ISSUE TITLE
MessagePack

### ISSUE THREAD

**Issue by troyedwardsjr** [5Mixer/mphx#46]
I see you've included MessagePack as a dependency. Are you still planning to use it for serialization?

**Comment by 5Mixer** [comment]
At the moment it isn't used in the library, no. Message pack did appeal because of it's tight serialisation and also because, like JSON, it isn't limited to haxe, and unlike JSON, is used outside the haxe realm, which is handy with a networking library. Although it isn't in the codebase, I am still planning on allowing serialization with it. If it turns out to be less efficient than the haxe one, then I may remove it. As of now though, it sticks :)
